spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev #开发环境
  application:
    name: EMPLOYEE-PROVIDER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
---
server:
  port: 8007
spring:
  profiles: test #测试环境
  application:
    name: EMPLOYEE-PROVIDER-TEST
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
